const { default: mongoose } = require("mongoose");
const Product = require("./models/Product");
require("dotenv").config();

const dummyJewelryProducts = [
  {
    title: "Elegant Gold Charm",
    price: 120,
    priceAfterDiscount: 99,
    color: ["gold"],
    size: ["6", "6.5"],
    description: "A beautiful gold charm with intricate detailing.",
    category: "charms",
    stock: 25,
    images: ["/images/1.jpg", "/images/2.jpg"],
    rating: 4.5,
  },
  {
    title: "Silver Hoop Earrings",
    price: 85,
    priceAfterDiscount: 70,
    color: ["silver"],
    size: ["1.2", "1.5"],
    description: "Stylish silver hoop earrings for everyday elegance.",
    category: "earrings",
    stock: 40,
    images: ["/images/3.jpg", "/images/4.jpg"],
    rating: 4.2,
  },
  {
    title: "Gold Diamond Ring",
    price: 300,
    priceAfterDiscount: 250,
    color: ["gold"],
    size: ["6", "7", "8"],
    description: "Exquisite gold ring with a single brilliant diamond.",
    category: "rings",
    stock: 10,
    images: ["/images/5.jpg", "/images/6.jpg"],
    rating: 4.9,
  },
  {
    title: "Silver Snake Necklace",
    price: 150,
    priceAfterDiscount: 130,
    color: ["silver"],
    size: ["16", "18", "20"],
    description: "Modern silver snake chain necklace.",
    category: "necklace",
    stock: 30,
    images: ["/images/7.jpg", "/images/8.jpg"],
    rating: 4.6,
  },
  {
    title: "Gold Link Bracelet",
    price: 110,
    priceAfterDiscount: 90,
    color: ["gold"],
    size: ["6.5", "7", "7.5"],
    description: "Timeless gold bracelet with interlocking links.",
    category: "bracelets",
    stock: 18,
    images: ["/images/9.jpg", "/images/10.jpg"],
    rating: 4.3,
  },
  {
    title: "Dual-Tone Earrings",
    price: 95,
    priceAfterDiscount: 80,
    color: ["gold", "silver"],
    size: ["1", "1.5"],
    description: "Elegant earrings combining both gold and silver tones.",
    category: "earrings",
    stock: 22,
    images: ["/images/11.jpg", "/images/12.jpg"],
    rating: 4.7,
  },
  {
    title: "Minimalist Ring Set",
    price: 60,
    priceAfterDiscount: 45,
    color: ["silver"],
    size: ["5.5", "6", "6.5"],
    description: "Set of 3 minimalist stacking rings.",
    category: "rings",
    stock: 35,
    images: ["/images/13.jpg", "/images/14.jpg"],
    rating: 4.1,
  },
  {
    title: "Pearl Charm Pendant",
    price: 140,
    priceAfterDiscount: 115,
    color: ["gold"],
    size: ["1.5"],
    description: "Gold charm with natural pearl center.",
    category: "charms",
    stock: 12,
    images: ["/images/15.jpg", "/images/16.jpg"],
    rating: 4.8,
  },
  {
    title: "Twisted Silver Bracelet",
    price: 105,
    priceAfterDiscount: 90,
    color: ["silver"],
    size: ["7", "7.5"],
    description: "Unique twisted design silver bracelet.",
    category: "bracelets",
    stock: 20,
    images: ["/images/17.jpg", "/images/18.jpg"],
    rating: 4.4,
  },
  {
    title: "Gold Choker Necklace",
    price: 180,
    priceAfterDiscount: 150,
    color: ["gold"],
    size: ["14", "15"],
    description: "Bold gold choker necklace for statement looks.",
    category: "necklace",
    stock: 14,
    images: ["/images/19.jpg", "/images/20.jpg"],
    rating: 4.6,
  },
];

const populateProducts = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  await Product.create(dummyJewelryProducts);
};

populateProducts();
